import { createHash } from 'crypto';
import { Actor, log } from 'apify';
import { gotScraping } from 'got-scraping';

await Actor.init();
const input = (await Actor.getInput()) ?? {};

const API = 'https://api.usaspending.gov/api/v2/search/spending_by_award/';
const PAGE_SIZE = 100; // API max for this endpoint

// award_type_codes must come from ONE group per request — mixing contract and grant codes
// returns HTTP 400 "must only contain types from one group". So each selected category is
// its own paginated query and the results are merged here.
const CATEGORIES = {
    contracts: { codes: ['A', 'B', 'C', 'D'], kind: 'contract' },
    idvs: { codes: ['IDV_A', 'IDV_B', 'IDV_B_A', 'IDV_B_B', 'IDV_B_C', 'IDV_C', 'IDV_D', 'IDV_E'], kind: 'contract' },
    grants: { codes: ['02', '03', '04', '05'], kind: 'assistance' },
    direct_payments: { codes: ['06', '10'], kind: 'assistance' },
    other_financial_assistance: { codes: ['09', '11', '-1'], kind: 'assistance' },
    loans: { codes: ['07', '08'], kind: 'loan' },
};

// Every award kind has its own field mapping on the API. These are the fields verified to
// come back with data; asking for a field outside its kind's mapping is a 400.
const BASE_FIELDS = [
    'Award ID', 'Recipient Name', 'Recipient UEI', 'recipient_id',
    'Awarding Agency', 'Awarding Sub Agency', 'Funding Agency', 'Funding Sub Agency',
    'Description', 'Last Modified Date', 'Base Obligation Date',
    'Place of Performance State Code', 'Place of Performance Country Code', 'Place of Performance Zip5', 'pop_city_name',
    'recipient_location_city_name', 'recipient_location_state_code', 'recipient_location_country_name',
    'recipient_location_address_line1', 'generated_internal_id', 'def_codes',
];
const KIND_FIELDS = {
    contract: ['Award Amount', 'Total Outlays', 'Start Date', 'End Date', 'Contract Award Type', 'NAICS', 'PSC'],
    assistance: ['Award Amount', 'Total Outlays', 'Start Date', 'End Date', 'Award Type', 'Assistance Listings'],
    loan: ['Loan Value', 'Subsidy Cost', 'Issued Date', 'Award Type', 'Assistance Listings'],
};
// The API rejects any `sort` value that is not also in `fields` — so sorts are per-kind too.
const SORTS = {
    awardAmount: { contract: 'Award Amount', assistance: 'Award Amount', loan: 'Loan Value' },
    lastModifiedDate: { contract: 'Last Modified Date', assistance: 'Last Modified Date', loan: 'Last Modified Date' },
    startDate: { contract: 'Start Date', assistance: 'Start Date', loan: 'Issued Date' },
    recipientName: { contract: 'Recipient Name', assistance: 'Recipient Name', loan: 'Recipient Name' },
};

// Sub-award rows come from the same endpoint with `subawards: true`, but they have their own
// field mapping — asking for a prime-award field (e.g. "Award Amount") there is a 400. This
// list is the API's own Sub-Award mapping, taken verbatim from its 400 error text.
const SUB_FIELDS = [
    'Sub-Award ID', 'Sub-Award Type', 'Sub-Awardee Name', 'Sub-Award Date', 'Sub-Award Amount',
    'Sub-Award Description', 'Sub-Recipient UEI',
    'Awarding Agency', 'Awarding Sub Agency',
    'Prime Award ID', 'Prime Recipient Name', 'Prime Award Recipient UEI', 'prime_award_recipient_id',
];
// Sub-awards carry no "last modified" date; that sort falls back to the sub-award action date.
const SUB_SORTS = {
    awardAmount: 'Sub-Award Amount',
    lastModifiedDate: 'Sub-Award Date',
    startDate: 'Sub-Award Date',
    recipientName: 'Sub-Awardee Name',
};

// startUrl: paste a usaspending.gov saved-search link instead of re-picking keyword/award-type
// filters by hand. The site stores every Advanced Search behind an opaque hash
// (usaspending.gov/search?hash=<32 hex> or /search/<32 hex>); api.usaspending.gov's own public,
// documented endpoint resolves that hash back into the filter object the UI built ("Accepts a
// hash generated by /api/v2/references/filter/ and returns an Advanced Search filter object" --
// api.usaspending.gov/docs/endpoints).
//
// Deliberately partial: the resolved object can also carry agency/location/NAICS/PSC/
// award-amount/date-range filters, but no live example this Actor could inspect (including
// usaspending.gov's own "search by keyword" blog posts, which is the mechanism's documented use
// case) ever populated those -- only `keyword` and (via the UI's award-type checkboxes)
// `awardType`. Mapping the others' nested shapes without a real populated example to check
// against would mean guessing, and a wrong guess silently drops or mis-applies a filter the
// pasted URL actually set. So only keyword and award-type are carried over; anything else
// present in the pasted search is named in a warning instead of silently dropped.
const startUrlInput = input.startUrl ? String(input.startUrl).trim() : null;
let startUrlKeywords = [];
let startUrlCategories = [];
if (startUrlInput) {
  let host;
  try {
    host = new URL(startUrlInput).hostname.replace(/^www\./, '');
  } catch {
    throw new Error(`"startUrl" is not a valid URL: ${JSON.stringify(startUrlInput)}`);
  }
  if (host !== 'usaspending.gov') {
    throw new Error(`"startUrl" must be a usaspending.gov link, got host ${JSON.stringify(host)}.`);
  }
  const hashMatch = startUrlInput.match(/[?&#]hash=([a-f0-9]{32})/i) ?? startUrlInput.match(/\/search\/([a-f0-9]{32})/i);
  if (!hashMatch) {
    throw new Error(
      '"startUrl" is a usaspending.gov link but no saved-search hash was found in it (expected '
      + '?hash=<32 hex chars> or /search/<32 hex chars>). Copy the link from the "Share" action '
      + 'on a usaspending.gov Advanced Search results page.',
    );
  }
  const hash = hashMatch[1].toLowerCase();
  let resolveResp;
  try {
    resolveResp = await gotScraping({
      url: 'https://api.usaspending.gov/api/v2/references/hash/',
      method: 'POST',
      json: { hash },
      responseType: 'json',
      throwHttpErrors: false,
    });
  } catch (err) {
    // Same network-level failure mode as postPage's retry loop, but this is a single pre-flight
    // call before any row is pushed or charged, so fail fast with a message that says what to do
    // instead of letting a raw TimeoutError surface as an unexplained crash.
    throw new Error(
      `"startUrl"'s saved-search hash (${hash}) could not be resolved: the request to `
      + `api.usaspending.gov failed (${err.message}). This is a network-level failure, not a bad `
      + 'link -- re-run the Actor; nothing was charged.',
    );
  }
  if (resolveResp.statusCode !== 200 || !resolveResp.body?.filter?.filters) {
    throw new Error(
      `"startUrl"'s saved-search hash (${hash}) could not be resolved (HTTP ${resolveResp.statusCode}). `
      + 'It may have expired, or the link was mistyped -- copy it fresh from usaspending.gov.',
    );
  }
  const resolved = resolveResp.body.filter.filters;
  const unapplied = [];

  const rawKeyword = resolved.keyword;
  if (rawKeyword && typeof rawKeyword === 'object') {
    const vals = Array.isArray(rawKeyword) ? rawKeyword : Object.values(rawKeyword);
    // The UI preserves the literal quote marks a buyer typed for a phrase search (e.g.
    // `"national monument"`); confirmed live against /api/v2/search/spending_by_award/ that
    // quoted and unquoted forms return identical results, so stripping them is cosmetic only.
    startUrlKeywords = vals.map((v) => String(v).trim().replace(/^"(.*)"$/, '$1')).filter(Boolean);
  }

  const rawAwardType = Array.isArray(resolved.awardType) ? resolved.awardType : [];
  if (rawAwardType.length) {
    const codeToCategory = new Map();
    for (const [name, def] of Object.entries(CATEGORIES)) {
      for (const code of def.codes) codeToCategory.set(code, name);
    }
    const matched = new Set();
    const unmatched = [];
    for (const code of rawAwardType) {
      const cat = codeToCategory.get(code);
      if (cat) matched.add(cat);
      else unmatched.push(code);
    }
    startUrlCategories = [...matched];
    if (unmatched.length) unapplied.push(`award type code(s) ${unmatched.join(', ')} (no matching category)`);
  }

  for (const [field, label] of [
    ['selectedAwardingAgencies', 'awarding agency'], ['selectedFundingAgencies', 'funding agency'],
    ['selectedRecipients', 'recipient'], ['selectedLocations', 'place of performance'],
    ['selectedRecipientLocations', 'recipient location'],
    ['awardAmounts', 'award amount'],
    ['time_period', 'custom date range'], ['timePeriodFY', 'fiscal year'],
  ]) {
    const v = resolved[field];
    const nonEmpty = v && (Array.isArray(v) ? v.length : Object.keys(v).length);
    if (nonEmpty) unapplied.push(label);
  }
  // naicsCodes/pscCodes are always `{require:[],exclude:[],counts:[]}` even when unset -- a
  // plain Object.keys().length check on them is always 3 and would false-positive every time
  // (caught by a real local run against a hash with no NAICS/PSC filter set).
  for (const [field, label] of [['naicsCodes', 'NAICS code'], ['pscCodes', 'PSC code']]) {
    const v = resolved[field];
    const nonEmpty = v && ['require', 'exclude', 'counts'].some((k) => Array.isArray(v[k]) && v[k].length);
    if (nonEmpty) unapplied.push(label);
  }
  if (unapplied.length) {
    log.warning(
      `"startUrl" also had a ${unapplied.join(', ')} filter set on usaspending.gov, but this Actor `
      + 'only carries the keyword and award-type filters over from a pasted link -- set the '
      + 'equivalent input (agencies/fundingAgencies/recipients/placeOfPerformanceStates/'
      + 'recipientStates/naicsCodes/pscCodes/minAwardAmount/maxAwardAmount/startDate/endDate) '
      + 'by hand if you need it too.',
    );
  }
  log.info(
    `"startUrl" resolved hash ${hash}: ${startUrlKeywords.length} keyword(s)`
    + (startUrlCategories.length ? `, award categories [${startUrlCategories.join(', ')}]` : ', no award-type filter')
    + '. These override the "keywords"/"awardCategories" inputs.',
  );
}

const isSubaward = String(input.awardLevel ?? 'prime').toLowerCase().trim() === 'subaward';

const categories = (startUrlCategories.length ? startUrlCategories : (input.awardCategories ?? ['contracts']))
    .map((c) => String(c).toLowerCase().trim())
    .filter((c) => Object.hasOwn(CATEGORIES, c));
if (!categories.length) categories.push('contracts');

const today = new Date();
const isoDay = (d) => d.toISOString().slice(0, 10);
// The API refuses time_period start dates before 2007-10-01.
const EARLIEST = '2007-10-01';
const endDate = input.endDate ? String(input.endDate).slice(0, 10) : isoDay(today);
const startDate = input.startDate
    ? String(input.startDate).slice(0, 10)
    : isoDay(new Date(today.getTime() - 365 * 86400_000));
const effectiveStart = startDate < EARLIEST ? EARLIEST : startDate;

const keywords = (startUrlKeywords.length ? startUrlKeywords : (input.keywords ?? [])).map((k) => String(k).trim()).filter(Boolean);
const agencies = (input.agencies ?? []).map((a) => String(a).trim()).filter(Boolean);
const fundingAgencies = (input.fundingAgencies ?? []).map((a) => String(a).trim()).filter(Boolean);
const recipients = (input.recipients ?? []).map((r) => String(r).trim()).filter(Boolean);
const awardIds = (input.awardIds ?? []).map((a) => String(a).trim()).filter(Boolean);
const states = (input.placeOfPerformanceStates ?? []).map((s) => String(s).trim().toUpperCase()).filter(Boolean);
const recipientStates = (input.recipientStates ?? []).map((s) => String(s).trim().toUpperCase()).filter(Boolean);
const recipientTypes = (input.recipientTypes ?? []).map((t) => String(t).trim().toLowerCase()).filter(Boolean);
const naicsCodes = (input.naicsCodes ?? []).map((c) => String(c).trim()).filter(Boolean);
// The API rejects anything but 1-4 uppercase alphanumerics with a 422, so uppercase here
// (buyers type "r425") and fail fast on the rest with a message that names the bad code.
const pscCodes = (input.pscCodes ?? []).map((c) => String(c).trim().toUpperCase()).filter(Boolean);
const badPsc = pscCodes.find((c) => !/^[A-Z0-9]{1,4}$/.test(c));
if (badPsc) {
  throw new Error(`"pscCodes" entry ${JSON.stringify(badPsc)} is not a PSC code — must be 1 to 4 letters/digits, e.g. "R425" (leaf), "R4" or "10" (prefix group), "R" (whole category).`);
}
const minAwardAmount = input.minAwardAmount != null ? Number(input.minAwardAmount) : null;
const maxAwardAmount = input.maxAwardAmount != null ? Number(input.maxAwardAmount) : null;
if (minAwardAmount != null && maxAwardAmount != null && minAwardAmount > maxAwardAmount) {
  throw new Error(`"minAwardAmount" (${minAwardAmount}) is greater than "maxAwardAmount" (${maxAwardAmount}) — no award can ever match. Swap them.`);
}
const expiringWithinDays = input.expiringWithinDays != null ? Number(input.expiringWithinDays) : null;
const expiringAfterDays = input.expiringAfterDays != null ? Number(input.expiringAfterDays) : null;
if (expiringWithinDays != null && (!Number.isFinite(expiringWithinDays) || expiringWithinDays < 1)) {
  throw new Error('"expiringWithinDays" must be a positive integer number of days.');
}
if (expiringAfterDays != null && (!Number.isFinite(expiringAfterDays) || expiringAfterDays < 0)) {
  throw new Error('"expiringAfterDays" must be a non-negative integer number of days.');
}
if (expiringAfterDays != null && expiringWithinDays == null) {
  log.warning('"expiringAfterDays" requires "expiringWithinDays" to also be set -- ignoring "expiringAfterDays".');
}
if (expiringAfterDays != null && expiringWithinDays != null && expiringAfterDays >= expiringWithinDays) {
  throw new Error(`"expiringAfterDays" (${expiringAfterDays}) must be less than "expiringWithinDays" (${expiringWithinDays}) — otherwise no award can ever match.`);
}
if (expiringWithinDays != null && isSubaward) {
  log.warning('"expiringWithinDays"/"expiringAfterDays" only apply in awardLevel="prime" mode -- sub-award records carry no period-of-performance end date. Ignoring.');
}
const includeOpportunityScore = Boolean(input.includeOpportunityScore);
if (includeOpportunityScore && isSubaward) {
  log.warning('"includeOpportunityScore" only applies in awardLevel="prime" mode -- sub-award records carry no period-of-performance end date to score recompete urgency from. Ignoring.');
}
const effectiveIncludeOpportunityScore = includeOpportunityScore && !isSubaward;
// Period-of-performance end date has no server-side filter on this API (its `time_period`
// date_type is restricted to action_date/date_signed/last_modified_date -- verified live,
// a "period_of_performance_current_end_date" date_type is rejected with a 400 naming the
// three valid values), so this is applied client-side against the "End Date" field this
// Actor already fetches for every contract/assistance row -- same "filter what we already
// have, before charging" shape as shopify's price filters.
const TODAY_UTC = new Date(`${new Date().toISOString().slice(0, 10)}T00:00:00Z`);
function daysUntilEnd(endDateStr) {
  if (!endDateStr) return null;
  const d = new Date(`${endDateStr}T00:00:00Z`);
  if (Number.isNaN(d.getTime())) return null;
  return Math.round((d - TODAY_UTC) / 86400000);
}
function passesExpiringFilter(item) {
  if (expiringWithinDays == null || isSubaward) return true;
  const days = daysUntilEnd(item.endDate);
  if (days == null || days < 0 || days > expiringWithinDays) return false;
  if (expiringAfterDays != null && days < expiringAfterDays) return false;
  return true;
}

// Deterministic (non-LLM) 0-100 "how worth pursuing is this" score, modeled on a smaller
// competitor's published "AI Opportunity Scoring" feature (confirmed cycle 549 to itself be a
// plain weighted formula, not an actual model call) -- every weight below is also spelled out
// in the README so it reads as a transparent heuristic, not a black box, matching this fleet's
// honesty standard for e.g. expiringWithinDays above.
const PRIORITY_TECH_TERMS = [
  'artificial intelligence', ' ai ', 'machine learning', 'cyber', 'cybersecurity', 'cloud computing',
  'cloud', 'solar', 'renewable energy', 'clean energy', 'quantum', 'robotics', 'autonomous',
  'biotechnology', 'biotech', 'semiconductor', 'data analytics',
];
// IDVs/BPAs are an ongoing multi-year vehicle (a relationship to pursue, not a one-off), so they
// score above a one-time definitive contract; grants/assistance/loans score lowest since this
// formula is aimed at recompete/bid-style opportunities, not funding awards.
const CATEGORY_TYPE_SCORE = { idvs: 15, contracts: 12, grants: 8, other_financial_assistance: 6, direct_payments: 5, loans: 4 };
function opportunityScore(item) {
  // 1) Award size, log-scaled 0-40 so a $50M+ mega-award doesn't swamp every other factor the
  //    way a linear scale would.
  const amount = item.awardAmount ?? 0;
  const amountScore = amount > 0 ? Math.min(40, (Math.log10(amount + 1) / Math.log10(50_000_000)) * 40) : 0;
  // 2) Tech/priority-sector keyword match, 0-25. Prefers the buyer's own "keywords" input (it
  //    already searched on them, so a hit there is the more relevant signal) and falls back to
  //    a fixed priority-sector list otherwise.
  const haystack = `${item.description ?? ''} ${item.naicsDescription ?? ''} ${item.pscDescription ?? ''}`.toLowerCase();
  const termList = keywords.length ? keywords.map((k) => k.toLowerCase()) : PRIORITY_TECH_TERMS;
  const keywordScore = termList.some((t) => haystack.includes(t)) ? 25 : 0;
  // 3) Award category, 0-15 (see CATEGORY_TYPE_SCORE comment above).
  const typeScore = CATEGORY_TYPE_SCORE[item.awardCategory] ?? 5;
  // 4) Recompete urgency, 0-20: higher the sooner the period of performance ends, 0 past 365
  //    days out or already expired -- same daysUntilEnd() used by expiringWithinDays above.
  const days = daysUntilEnd(item.endDate);
  const urgencyScore = (days != null && days >= 0 && days <= 365) ? Math.round(20 * (1 - days / 365)) : 0;
  return Math.round(Math.min(100, amountScore + keywordScore + typeScore + urgencyScore));
}
const sortBy = Object.hasOwn(SORTS, input.sortBy) ? input.sortBy : 'awardAmount';
const order = input.order === 'asc' ? 'asc' : 'desc';
const maxResults = Math.min(Math.max(Number(input.maxResults ?? 100), 1), 10000);
const maxPagesPerCategory = Math.min(Math.max(Number(input.maxPagesPerCategory ?? 50), 1), 200);
const watchLabel = String(input.watchLabel ?? '').trim();
const watchChanges = Boolean(input.watchChanges);

// Convenience completion ping (same shape as grants-gov-scraper, cycle 421). A bad value is
// warned and ignored rather than thrown -- this is a notification nicety, not core function.
const webhookUrlRaw = String(input.webhookUrl ?? '').trim();
let webhookUrl = null;
if (webhookUrlRaw) {
    try {
        const parsed = new URL(webhookUrlRaw);
        if (parsed.protocol === 'http:' || parsed.protocol === 'https:') webhookUrl = parsed.toString();
        else log.warning(`webhookUrl "${webhookUrlRaw}" is not http(s); ignoring.`);
    } catch {
        log.warning(`webhookUrl "${webhookUrlRaw}" is not a valid URL; ignoring.`);
    }
}

// Watch mode: a stateful "only new awards/sub-awards since my last run" filter. Both prime
// and sub-award mode have a real "new since last time" concept (new awards get made, new
// sub-awards get filed), unlike FEC's candidates mode which returns a fixed roster. The
// baseline (award/sub-award ids already delivered under this label+filter set) lives in a
// NAMED key-value store on the buyer's own account so it survives across runs.
const WATCH_STORE = 'fetchsmith-usaspending-watch';
const SEED_CAP = 20000; // bound the cost of a baseline run against a broad/unfiltered category
const WATCH_KEEP = 20000; // bound the record size; oldest ids fall off first
// Per-category page cap used only while seeding, independent of the buyer's own
// maxPagesPerCategory cost cap -- same fix as eu-ted-tenders/uk-find-a-tender: the buyer's
// own scan-depth budget must never also bound how comprehensive a baseline is, or an
// incremental run would report older, merely-unscanned awards as "new".
const SEED_PAGE_CAP = 1000;

function watchKeyFor(label, criteria) {
  const safe = label.toLowerCase().replace(/[^a-z0-9_.-]+/g, '-').replace(/^-+|-+$/g, '').slice(0, 40) || 'default';
  const fp = createHash('sha1').update(JSON.stringify(criteria, Object.keys(criteria).sort())).digest('hex').slice(0, 10);
  return { key: `watch-${safe}-${fp}`, fingerprint: fp };
}

const watchMode = watchLabel.length > 0;
// watchChanges only makes sense in prime mode: sub-award records carry no reliable
// last-modified/amount drift signal (subAwardDate is a static filing date), unlike prime
// awards where USAspending's own "Last Modified Date" plus amount/outlays/end-date are thin
// fields that genuinely mutate post-publication (change orders, option exercises, extensions).
const effectiveWatchChanges = watchChanges && !isSubaward;
if (watchMode && watchChanges && isSubaward) {
  log.warning(
    '"watchChanges" is only supported in awardLevel="prime" mode -- sub-award records have no '
    + 'reliable drift signal to compare against. Ignoring the flag; watch mode still alerts on genuinely new sub-awards.',
  );
}
let watchStore = null;
let watchKey = null;
let watchRecord = null;
let seeding = false;
let watchSkipped = 0;
let changedCount = 0;
// award/sub-award id -> last-seen snapshot of thin fields (already fetched, no extra API
// calls) that can change on an otherwise-already-delivered PRIME award: lastModifiedDate
// (USAspending's own "this record changed" signal), awardAmount/totalOutlays (contracts and
// assistance) or loanValue/subsidyCost (loans), and endDate (period-of-performance
// extensions). effectiveWatchChanges decides whether a change re-delivers the row; the
// snapshot itself is always kept current so turning the flag on later detects only future
// drift, not a backlog since the baseline.
const watchSeen = new Map();

function snapshotOf(item) {
  return {
    lastModifiedDate: item.lastModifiedDate ?? null,
    awardAmount: item.awardAmount ?? null,
    totalOutlays: item.totalOutlays ?? null,
    loanValue: item.loanValue ?? null,
    subsidyCost: item.subsidyCost ?? null,
    endDate: item.endDate ?? null,
  };
}

// A changed award is re-delivered with these fields describing exactly what moved, so a buyer
// doesn't have to diff the row against their own last-seen copy to find out.
function changesBetween(prev, next) {
  if (!prev) return null;
  const types = [];
  const previous = {};
  for (const field of ['lastModifiedDate', 'awardAmount', 'totalOutlays', 'loanValue', 'subsidyCost', 'endDate']) {
    if (prev[field] !== undefined && prev[field] !== null && prev[field] !== next[field]) {
      types.push(field);
      previous[field] = prev[field];
    }
  }
  return types.length ? { types, previous } : null;
}

if (watchMode) {
  // When awardIds is set every other filter is dropped by buildFilters (exact-ID lookup), so
  // the fingerprint follows that override instead of also keying on filters with no effect on
  // the actual query sent -- same rule eu-ted-tenders applies to its expertQuery override.
  const criteria = awardIds.length
    ? { awardLevel: isSubaward ? 'subaward' : 'prime', awardIds: [...awardIds].sort() }
    : {
      awardLevel: isSubaward ? 'subaward' : 'prime',
      categories: [...categories].sort(),
      keywords: [...keywords].sort(),
      agencies: [...agencies].sort(),
      fundingAgencies: [...fundingAgencies].sort(),
      recipients: [...recipients].sort(),
      states: [...states].sort(),
      recipientStates: [...recipientStates].sort(),
      recipientTypes: [...recipientTypes].sort(),
      naicsCodes: [...naicsCodes].sort(),
      pscCodes: [...pscCodes].sort(),
      minAwardAmount: minAwardAmount ?? null,
      maxAwardAmount: maxAwardAmount ?? null,
      // Raw day counts, not resolved dates -- the countdown moves every day on its own (same
      // rolling-default rule as startDate/endDate below), but the buyer's chosen thresholds
      // don't, so fingerprinting the raw numbers doesn't force a fresh baseline daily.
      expiringWithinDays: expiringWithinDays ?? null,
      expiringAfterDays: expiringAfterDays ?? null,
      // Raw buyer input, not the resolved value -- startDate/endDate default to "one year
      // ago"/"today" and roll forward every single day, so fingerprinting the resolved value
      // would force a fresh baseline daily (a daily version of the cycle-297 FEC electionYear
      // trap, which only rolls every two years).
      startDateRaw: input.startDate ?? null,
      endDateRaw: input.endDate ?? null,
    };
  watchStore = await Actor.openKeyValueStore(WATCH_STORE);
  const { key, fingerprint } = watchKeyFor(watchLabel, criteria);
  watchKey = key;
  const existing = await watchStore.getValue(key);
  if (existing && Array.isArray(existing.seenIds)) {
    watchRecord = existing;
    // Pre-change-tracking records stored `seenIds` as a flat array of id strings (every
    // record predates this feature) -- those ids get a null snapshot, so effectiveWatchChanges
    // only starts detecting drift from this run onward, never against a backlog it never captured.
    for (const entry of existing.seenIds) {
      if (entry && typeof entry === 'object') {
        watchSeen.set(String(entry.i), {
          lastModifiedDate: entry.m ?? null,
          awardAmount: entry.a ?? null,
          totalOutlays: entry.o ?? null,
          loanValue: entry.l ?? null,
          subsidyCost: entry.s ?? null,
          endDate: entry.e ?? null,
        });
      } else {
        watchSeen.set(String(entry), {
          lastModifiedDate: null, awardAmount: null, totalOutlays: null, loanValue: null, subsidyCost: null, endDate: null,
        });
      }
    }
    log.info(
      `Watch mode "${watchLabel}" (${key}): baseline from ${existing.lastRunAt ?? 'an earlier run'} holds `
      + `${watchSeen.size} already-delivered award(s)/sub-award(s). Only ones NOT in that baseline will be returned and charged`
      + (effectiveWatchChanges ? ', plus any already-delivered prime award whose last-modified date, amount, outlays or end date changed.' : '.'),
    );
  } else {
    watchRecord = { fingerprint, firstSeededAt: new Date().toISOString(), runCount: 0 };
    seeding = true;
    log.info(
      `Watch mode "${watchLabel}" (${key}): FIRST run for this label and filter set, so this is a baseline `
      + 'run. It records which awards/sub-awards already match and returns ZERO results (you are charged nothing). '
      + 'Run it again on the same label and filters -- on a schedule, typically -- to get only what is new since now.',
    );
  }
}

async function saveWatchRecord(status) {
  const entries = Array.from(watchSeen.entries()).slice(-WATCH_KEEP);
  await watchStore.setValue(watchKey, {
    ...watchRecord,
    label: watchLabel,
    lastRunAt: new Date().toISOString(),
    lastRunStatus: status,
    runCount: (watchRecord.runCount ?? 0) + 1,
    seenCount: entries.length,
    // Compact per-entry shape (id + 6 short-keyed snapshot fields) -- WATCH_KEEP can hold up
    // to 20,000 of these in one KV record.
    seenIds: entries.map(([id, snap]) => ({
      i: id, m: snap.lastModifiedDate, a: snap.awardAmount, o: snap.totalOutlays, l: snap.loanValue, s: snap.subsidyCost, e: snap.endDate,
    })),
  });
}

function buildFilters(codes) {
    const filters = {
        award_type_codes: codes,
        time_period: [{ start_date: effectiveStart, end_date: endDate }],
    };
    // Exact-ID lookup is exclusive: every other filter is dropped and the date window is
    // widened to the API's full supported range, so an award_ids match can never be silently
    // hidden by an unrelated filter — same trap class as grants-gov's oppNum, clinicaltrials'
    // nctIds and nih-reporter's projectNums.
    if (awardIds.length) {
        filters.award_ids = awardIds;
        filters.time_period = [{ start_date: EARLIEST, end_date: isoDay(today) }];
        return filters;
    }
    if (keywords.length) filters.keywords = keywords;
    if (recipients.length) filters.recipient_search_text = recipients;
    if (agencies.length || fundingAgencies.length) {
        filters.agencies = [
            ...agencies.map((name) => ({ type: 'awarding', tier: 'toptier', name })),
            ...fundingAgencies.map((name) => ({ type: 'funding', tier: 'toptier', name })),
        ];
    }
    if (states.length) {
        filters.place_of_performance_locations = states.map((state) => ({ country: 'USA', state }));
    }
    if (recipientStates.length) {
        filters.recipient_locations = recipientStates.map((state) => ({ country: 'USA', state }));
    }
    if (recipientTypes.length) filters.recipient_type_names = recipientTypes;
    if (minAwardAmount != null || maxAwardAmount != null) {
        const bound = {};
        if (minAwardAmount != null) bound.lower_bound = minAwardAmount;
        if (maxAwardAmount != null) bound.upper_bound = maxAwardAmount;
        filters.award_amounts = [bound];
    }
    // 2/4/6-digit NAICS prefixes are all accepted and ORed by the API; grants/loans have no
    // NAICS so this filter just returns nothing for those categories rather than erroring.
    if (naicsCodes.length) filters.naics_codes = { require: naicsCodes };
    // PSC takes the flat-list form (NOT the tiered ["Service","R","R4","R425"] paths the
    // filter-tree endpoint returns — those only work inside `require`). 1-4 char prefixes are
    // all accepted and ORed, verified: R425 17,465 + R499 71,409 = 88,874 for the pair, exactly.
    // Only contracts/IDVs carry a PSC, so grants/loans/direct payments return nothing here.
    if (pscCodes.length) filters.psc_codes = pscCodes;
    return filters;
}

const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

async function postPage(body) {
    for (let attempt = 1; attempt <= 4; attempt += 1) {
        let resp;
        try {
            resp = await gotScraping({
                url: API,
                method: 'POST',
                json: body,
                responseType: 'text', // error bodies are not always JSON; parse explicitly
                throwHttpErrors: false,
                retry: { limit: 0 },
                timeout: { request: 60000 },
                headers: { accept: 'application/json', 'content-type': 'application/json' },
            });
        } catch (err) {
            // A network-level failure (timeout, ECONNRESET, DNS) throws instead of resolving with
            // a status code — without this catch it crashes the whole run instead of retrying like
            // a 429/5xx does, even though the same backoff is exactly as valid here.
            const waitS = attempt * 10;
            log.warning(`USAspending request failed (${err.message}); retrying in ${waitS}s (${attempt}/4).`);
            await sleep(waitS * 1000);
            continue;
        }

        if (resp.statusCode === 429 || resp.statusCode >= 500) {
            const waitS = Number(resp.headers['retry-after']) || attempt * 10;
            log.warning(`USAspending returned ${resp.statusCode}; retrying in ${waitS}s (${attempt}/4).`);
            await sleep(waitS * 1000);
            continue;
        }
        let parsed = null;
        try { parsed = JSON.parse(resp.body); } catch { /* handled below */ }
        if (resp.statusCode !== 200) {
            const detail = parsed?.detail ?? parsed?.message ?? String(resp.body).slice(0, 300);
            log.warning(`USAspending API ${resp.statusCode}: ${detail}`);
            return null;
        }
        if (!parsed) {
            log.warning(`USAspending returned a non-JSON body: ${String(resp.body).slice(0, 200)}`);
            return null;
        }
        return parsed;
    }
    log.warning('USAspending kept rate-limiting/erroring after 4 attempts; stopping this category early.');
    return null;
}

function uniq(arr) {
    return Array.from(new Set((arr ?? []).filter((v) => v != null && v !== '')));
}

function normalize(r, category, kind) {
    const gid = r.generated_internal_id ?? null;
    const listings = r['Assistance Listings'] ?? [];
    return {
        awardId: r['Award ID'] ?? null,
        awardUrl: gid ? `https://www.usaspending.gov/award/${encodeURIComponent(gid)}` : null,
        generatedInternalId: gid,
        awardLevel: 'prime',
        awardCategory: category,
        awardType: r['Contract Award Type'] ?? r['Award Type'] ?? null,

        recipientName: r['Recipient Name'] ?? null,
        recipientUei: r['Recipient UEI'] ?? null,
        recipientId: r.recipient_id ?? null,
        recipientAddress: r.recipient_location_address_line1 ?? null,
        recipientCity: r.recipient_location_city_name ?? null,
        recipientState: r.recipient_location_state_code ?? null,
        recipientCountry: r.recipient_location_country_name ?? null,

        awardingAgency: r['Awarding Agency'] ?? null,
        awardingSubAgency: r['Awarding Sub Agency'] ?? null,
        fundingAgency: r['Funding Agency'] ?? null,
        fundingSubAgency: r['Funding Sub Agency'] ?? null,

        description: r.Description ?? null,

        // Loans report money as face value + subsidy cost instead of obligated/outlayed amounts.
        awardAmount: typeof r['Award Amount'] === 'number' ? r['Award Amount'] : null,
        totalOutlays: typeof r['Total Outlays'] === 'number' ? r['Total Outlays'] : null,
        loanValue: typeof r['Loan Value'] === 'number' ? r['Loan Value'] : null,
        subsidyCost: typeof r['Subsidy Cost'] === 'number' ? r['Subsidy Cost'] : null,

        startDate: r['Start Date'] ?? r['Issued Date'] ?? null,
        endDate: r['End Date'] ?? null,
        baseObligationDate: r['Base Obligation Date'] ?? null,
        lastModifiedDate: r['Last Modified Date'] ?? null,

        placeOfPerformanceCity: r.pop_city_name ?? null,
        placeOfPerformanceState: r['Place of Performance State Code'] ?? null,
        placeOfPerformanceZip: r['Place of Performance Zip5'] ?? null,
        placeOfPerformanceCountry: r['Place of Performance Country Code'] ?? null,

        naicsCode: r.NAICS?.code ?? null,
        naicsDescription: r.NAICS?.description ?? null,
        pscCode: r.PSC?.code ?? null,
        pscDescription: r.PSC?.description ?? null,
        cfdaNumbers: uniq(listings.map((l) => l.cfda_number)),
        cfdaProgramTitles: uniq(listings.map((l) => l.cfda_program_title)),
        disasterEmergencyFundCodes: uniq(r.def_codes),

        kind,
    };
}

function normalizeSub(r, category) {
    const primeGid = r.prime_award_generated_internal_id ?? null;
    return {
        awardLevel: 'subaward',
        subAwardId: r['Sub-Award ID'] ?? null,
        subAwardType: r['Sub-Award Type'] ?? null,
        subAwardDate: r['Sub-Award Date'] ?? null,
        subAwardAmount: typeof r['Sub-Award Amount'] === 'number' ? r['Sub-Award Amount'] : null,
        subAwardDescription: r['Sub-Award Description'] ?? null,

        subRecipientName: r['Sub-Awardee Name'] ?? null,
        subRecipientUei: r['Sub-Recipient UEI'] ?? null,

        primeAwardId: r['Prime Award ID'] ?? null,
        primeRecipientName: r['Prime Recipient Name'] ?? null,
        primeRecipientUei: r['Prime Award Recipient UEI'] ?? null,
        primeRecipientId: r.prime_award_recipient_id ?? null,
        primeAwardGeneratedInternalId: primeGid,
        // Same URL shape as a prime row's awardUrl, so a sub-award row can be joined straight
        // back to the prime award page (or to a prime-level run of this Actor).
        primeAwardUrl: primeGid ? `https://www.usaspending.gov/award/${encodeURIComponent(primeGid)}` : null,

        awardingAgency: r['Awarding Agency'] ?? null,
        awardingSubAgency: r['Awarding Sub Agency'] ?? null,

        awardCategory: category,
        kind: 'subaward',
    };
}

let pushed = 0;
let beforePush = 0;
const isPPE = Actor.getChargingManager().getPricingInfo().isPayPerEvent;
async function pushResult(item) {
    if (isPPE) {
        const r = await Actor.charge({ eventName: 'result', count: 1 });
        if (r.chargedCount === 0) return false;
        await Actor.pushData(item); pushed += 1;
        return !r.eventChargeLimitReached && pushed < maxResults;
    }
    await Actor.pushData(item); pushed += 1;
    return pushed < maxResults;
}

if (awardIds.length) {
    log.info(
        `USAspending: exact award-ID lookup awardIds=[${awardIds.join(', ')}] (all other filters ignored) maxResults=${maxResults}`
        + (isSubaward ? ' — in subaward mode these are PRIME award IDs; every sub-award under them is returned' : ''),
    );
} else {
    log.info(
        `USAspending: level=${isSubaward ? 'subaward' : 'prime'} categories=[${categories.join(',')}] ${effectiveStart}..${endDate} `
        + `sort=${sortBy} ${order} maxResults=${maxResults}`
        + (keywords.length ? ` keywords=[${keywords.join(', ')}]` : '')
        + (recipients.length ? ` recipients=[${recipients.join(', ')}]` : '')
        + (agencies.length ? ` agencies=[${agencies.join(', ')}]` : '')
        + (fundingAgencies.length ? ` fundingAgencies=[${fundingAgencies.join(', ')}]` : '')
        + (naicsCodes.length ? ` naicsCodes=[${naicsCodes.join(', ')}]` : '')
        // Log the codes as actually sent (uppercased): an unrecognised PSC returns zero rows
        // instead of erroring, so this line is what makes an empty run diagnosable.
        + (pscCodes.length ? ` pscCodes=[${pscCodes.join(', ')}]` : ''),
    );
}

const seen = new Set();
let scanned = 0;
let keepGoing = true;

for (const category of categories) {
    if (!keepGoing || pushed >= maxResults) break;
    const { codes, kind } = CATEGORIES[category];
    const fields = isSubaward ? SUB_FIELDS : [...BASE_FIELDS, ...KIND_FIELDS[kind]];
    const sort = isSubaward ? SUB_SORTS[sortBy] : SORTS[sortBy][kind];
    const filters = buildFilters(codes);
    // While seeding a watch baseline, scan deeper than the buyer's own maxPagesPerCategory so
    // the baseline reflects the whole current match set, not just its first N pages. Incremental
    // runs keep the buyer's own cap unchanged: it's an honest scan-depth cost control here (see
    // its schema description), not a delivery limit doing double duty as one (unlike the
    // ats-jobs/hacker-news traps), so it's the buyer's own choice for a normal run either way.
    const pageCap = seeding ? Math.max(maxPagesPerCategory, SEED_PAGE_CAP) : maxPagesPerCategory;

    let page = 1;
    let categoryRows = 0;
    while (keepGoing && pushed < maxResults && page <= pageCap) {
        const body = await postPage({ filters, fields, page, limit: PAGE_SIZE, sort, order, subawards: isSubaward });
        if (!body) break;
        const results = body.results ?? [];
        if (!results.length) break;
        scanned += results.length;

        for (const row of results) {
            const key = isSubaward
                ? `sub:${row.internal_id ?? row['Sub-Award ID']}`
                : row.generated_internal_id ?? `${category}:${row.internal_id}`;
            if (seen.has(key)) continue;
            seen.add(key);
            categoryRows += 1;
            const item = isSubaward ? normalizeSub(row, category) : normalize(row, category, kind);
            if (effectiveIncludeOpportunityScore) item.opportunityScore = opportunityScore(item);
            if (!passesExpiringFilter(item)) continue;

            if (watchMode && seeding) {
                watchSeen.set(key, snapshotOf(item));
                keepGoing = watchSeen.size < SEED_CAP;
                if (!keepGoing) break;
                continue;
            }
            if (watchMode && watchSeen.has(key)) {
                // Already delivered under this watch label. Normally dropped before any charge,
                // so an award is never paid for twice -- UNLESS effectiveWatchChanges is on and
                // its snapshot drifted since we last saw it, in which case it is re-delivered
                // (charged like a new row) tagged with exactly what changed.
                const nextSnap = snapshotOf(item);
                const change = effectiveWatchChanges ? changesBetween(watchSeen.get(key), nextSnap) : null;
                if (!change) {
                    // Snapshot kept current either way, so enabling the flag later detects only
                    // drift from that point, not a backlog since the baseline.
                    watchSeen.set(key, nextSnap);
                    watchSkipped += 1;
                    continue;
                }
                keepGoing = await pushResult({ ...item, _watchChangeType: change.types, _watchPrevious: change.previous });
                if (pushed > beforePush) { watchSeen.set(key, nextSnap); changedCount += 1; }
                beforePush = pushed;
                if (!keepGoing) break;
                continue;
            }

            keepGoing = await pushResult(item);
            // Recorded as delivered only after the charge actually succeeded -- anything dropped
            // by maxResults or a charge limit stays "new" for the next run.
            if (watchMode && pushed > beforePush) watchSeen.set(key, snapshotOf(item));
            beforePush = pushed;
            if (!keepGoing) break;
        }
        log.info(`${category} page ${page}: ${results.length} ${isSubaward ? 'sub-awards' : 'awards'} (pushed ${pushed}/${maxResults})`);
        if (!body.page_metadata?.hasNext) break;
        page += 1;
    }
    log.info(`${category}: pushed ${categoryRows} ${isSubaward ? 'sub-awards' : 'awards'}.`);
}

if (watchMode) {
    await saveWatchRecord(seeding ? 'seeded' : 'incremental');
    if (seeding) {
        log.info(
            `Baseline saved for watch label "${watchLabel}": ${watchSeen.size} award(s)/sub-award(s) recorded as `
            + 'already-seen, 0 results returned, 0 charged. The next run on this label and these filters returns '
            + 'only what is new.'
            + (watchSeen.size >= SEED_CAP
                ? ` NOTE: the baseline hit the ${SEED_CAP}-record cap. Narrow the filters so the whole current match `
                    + 'set fits, or the first incremental run may report older, merely-unscanned awards as new.'
                : ''),
        );
        await Actor.setStatusMessage(`Baseline run for watch label "${watchLabel}": ${watchSeen.size} existing award(s)/sub-award(s) recorded, 0 charged. Run again later to get only what's new.`);
    } else {
        log.info(
            `Watch label "${watchLabel}": ${pushed - changedCount} new award(s)/sub-award(s)`
            + (effectiveWatchChanges ? ` and ${changedCount} changed prime award(s) (last-modified/amount/outlays/end date)` : '')
            + ` since the last run (${watchSkipped} already-delivered, unchanged hit(s) skipped, not charged); baseline now holds ${watchSeen.size}.`,
        );
        if (pushed === 0) {
            await Actor.setStatusMessage(`Nothing new for watch label "${watchLabel}" since its last run -- every matching award/sub-award had already been delivered. That is the expected result most of the time; you were charged for nothing.`);
        }
    }
}

if (pushed === 0 && !watchMode) {
    log.warning(
        `No awards matched. Scanned ${scanned} rows. Most common causes, in order: `
        + '(1) the filters are ANDed — a keyword plus a state plus a minimum amount over a short date window '
        + 'often has zero real matches; drop one filter and retry. '
        + '(2) "agencies" must be the exact top-tier agency name as USAspending spells it '
        + '(e.g. "Department of Energy", not "DOE" or "Energy"). '
        + '(3) the date window is USAspending\'s award-level time_period filter, a coarse recency '
        + 'bound rather than a strict window — widen "startDate"/"endDate", and move the END date, '
        + 'which is what actually changes the result set '
        + '(dates before 2007-10-01 are not supported by the API and are clamped). '
        + '(4) state codes must be 2-letter USPS codes (CA, TX). Rows that match nothing are never charged.'
        + (isSubaward
            ? ' (5) awardLevel="subaward" only covers prime awards whose recipient filed FSRS sub-award reports — '
                + 'small awards and most loans/direct payments have none; try awardLevel="prime" to confirm the prime award exists.'
            : '')
        + (expiringWithinDays != null
            ? ` (${isSubaward ? 6 : 5}) "expiringWithinDays"=${expiringWithinDays}${expiringAfterDays != null ? ` with "expiringAfterDays"=${expiringAfterDays}` : ''} `
                + 'is a narrow window and only counts contracts/grants/IDVs (not loans, which report no period-of-performance end date) — try widening it or dropping it to confirm awards exist at all first.'
            : ''),
    );
}

log.info(`Done. Scanned ${scanned} ${isSubaward ? 'sub-awards' : 'awards'}, pushed ${pushed}.`);

// Fires after every row is already pushed and charged, so a slow or failing webhook can never
// affect the result set or the bill -- best-effort only, one attempt, short timeout, failures are
// a warning not a thrown error.
if (webhookUrl) {
    const env = Actor.getEnv();
    const payload = {
        actorRunId: env.actorRunId ?? null,
        defaultDatasetId: env.defaultDatasetId ?? null,
        finishedAt: new Date().toISOString(),
        pushed,
        scanned,
        watchLabel: watchMode ? watchLabel : null,
        watchSeeding: watchMode ? seeding : null,
        watchNewCount: watchMode && !seeding ? pushed - changedCount : null,
        watchChangedCount: watchMode && !seeding ? changedCount : null,
    };
    try {
        const resp = await gotScraping({
            url: webhookUrl,
            method: 'POST',
            responseType: 'text',
            throwHttpErrors: false,
            retry: { limit: 0 },
            timeout: { request: 10000 },
            headers: { 'content-type': 'application/json' },
            body: JSON.stringify(payload),
        });
        if (resp.statusCode >= 400) log.warning(`webhookUrl POST returned ${resp.statusCode}; run result is unaffected.`);
        else log.info(`Posted completion summary to webhookUrl (${resp.statusCode}).`);
    } catch (err) {
        log.warning(`webhookUrl POST failed (${err.message}); run result is unaffected.`);
    }
}

await Actor.exit();
